name: SBOM & Grype Scan

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  sbom-grype:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM (spdx-json)
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: bom.json

      - name: Generate bom.txt with aligned columns
        run: |
          {
            echo -e "NAME\tVERSION\tTYPE\tFILE"
            jq -r '
              .packages[]? |
              .name as $n |
              (.versionInfo // "-") as $v |
              (.SPDXID // "" | capture("SPDXRef-Package-(?<type>[^-]+)") | .type // "-") as $t |
              (
                if (.sourceInfo? != null and (.sourceInfo | test("paths: "))) then
                  (.sourceInfo | capture("paths: (?<f>[^\\s]+)") | .f // "-")
                else
                  "-"
                end
              ) as $f |
              "\($n)\t\($v)\t\($t)\t\($f)"
            ' bom.json
          } | column -t -s $'\t' > bom.txt

      - name: Upload human-readable SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-table
          path: bom.txt

      - name: Output SBOM summary to GitHub Actions UI
        run: |
          echo "### SBOM Summary (first 30 lines)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          head -n 30 bom.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Grype scan with SBOM (SARIF format)
        uses: anchore/scan-action@v6
        with:
          sbom: bom.json
          output-format: sarif
          output-file: grype-results.sarif
          fail-build: false

      - name: Upload Grype SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-sarif
          path: grype-results.sarif

      - name: Install Grype CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Grype scan (table format)
        run: |
          grype sbom:./bom.json -o table > grype-results.txt

      - name: Upload Grype text results
        uses: actions/upload-artifact@v4
        with:
          name: grype-table
          path: grype-results.txt

      - name: Output Grype summary to GitHub Actions UI
        run: |
          echo "### Grype Results (first 30 lines)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          head -n 30 grype-results.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
